### ISSUE TITLE
Python demo is missing

### ISSUE THREAD

**Issue by OzymoGit** [ZCban/kmboxNET#2]
hello, I am verry appeciate your work here.
I have some problem implenting a working python script for kmboxnet.
That is there is no function for mouse click? also the km.move is missing, I remember there is a auto curve function for it? is it not.
Thanks

**Comment by ZCban** [comment]
I think you are referring to this function kmNet_mouse_all(int button, int x, int y, int wheel). to control the simple click it would be km.left(1) holds the click down km.left(0) releases it. if you have any doubts, look in the visual code section under kmboxNet.h to find all the functions and how to use them

**Comment by OzymoGit** [comment]
> I think you are referring to this function kmNet_mouse_all(int button, int x, int y, int wheel). to control the simple click it would be km.left(1) holds the click down km.left(0) releases it. if you have any doubts, look in the visual code section under kmboxNet.h to find all the functions and how to use them

thanks, I will try it again.

**Comment by OzymoGit** [comment]
> I think you are referring to this function kmNet_mouse_all(int button, int x, int y, int wheel). to control the simple click it would be km.left(1) holds the click down km.left(0) releases it. if you have any doubts, look in the visual code section under kmboxNet.h to find all the functions and how to use them

I cant make it to works.

can you make a demo about sending all mouse movement and click, wheel from host pc to kmbox net?

**Comment by ZCban** [comment]
import kmNet
kmNet.init('192.168.2.188','1408','9FC05414')

deltay=target0
delta_y= target1
if len (target) >0:
       kmNet.move_auto(delta_x, delta_y, 2)
       kmNet.left(1)
       kmNet.left(0)
